import { describe, it, expect } from 'vitest';
import crypto from 'node:crypto';
import {
  WolverineProductionCluster,
  createSignedCustomerCommitment,
  WolverineProductionCli,
} from '../../src/index.js';

describe('Compromised Wolverine Gateway Defense (WDB-0100, WDB-0103)', () => {
  const genKeys = () => {
    const pair = crypto.generateKeyPairSync('ed25519');
    const pub = pair.publicKey.export({ type: 'spki', format: 'der' }).subarray(-32);
    return { pub, priv: pair.privateKey };
  };

  it('rogue gateway attack: attempts to forge conflicting digest for Checkpoint 1842 -> all 5 validators reject and fail closed', async () => {
    const cluster = new WolverineProductionCluster({ totalValidators: 5, requiredQuorum: 4 });
    const customer = genKeys();
    cluster.registerTenant('enterprise-alpha', customer.pub, 'production-orders');

    // 1. Customer legitimately commits Checkpoint 1842
    const originalCommitment = createSignedCustomerCommitment(
      {
        commitmentId: crypto.randomUUID(),
        tenantId: 'enterprise-alpha',
        databaseId: 'production-orders',
        checkpointId: '00000000-0000-0000-0000-000000001842',
        commitSeq: 1842n,
        checkpointDigest: Buffer.alloc(32, 0xaa),
        previousTrustCommitment: Buffer.alloc(32, 0),
      },
      customer.priv,
      customer.pub
    );

    const legitResult = await cluster.submitCommitment(originalCommitment);
    expect(legitResult.certificate.quorumCount).toBe(5);
    expect(legitResult.certificate.finalityStatus).toBe('FINALIZED');

    // 2. ATTACKER COMPROMISES WOLVERINE GATEWAY & ATTEMPTS TO FORGE DIGEST 0xBB FOR SEQ 1842
    const fakeDigest = Buffer.alloc(32, 0xbb);
    const attackResult = await cluster.adversarySimulator.attackConflictingCommitment(
      originalCommitment,
      fakeDigest,
      customer.pub,
      customer.priv
    );

    expect(attackResult.isBlocked).toBe(true);
    expect(attackResult.finalityGranted).toBe(false);
    expect(attackResult.validatorsRejectedCount).toBe(5);

    // Verify slashing evidence generated by validators
    for (const val of cluster.validators.values()) {
      const evidence = val.getSlashingEvidence();
      expect(evidence.length).toBe(1);
      expect(evidence[0]?.proofType).toBe('CONFLICTING_COMMITMENT');
      expect(evidence[0]?.commitSeq).toBe('1842');
    }

    // CLI Inspection
    const inspectOutput = WolverineProductionCli.executeInspectAdversary(attackResult);
    expect(inspectOutput).toContain('WOLVERINE ADVERSARIAL ATTACK DEFENSE INSPECTION');
    expect(inspectOutput).toContain('Attack Blocked:           YES (DEFENSE SUCCESS)');
    expect(inspectOutput).toContain('Finality Granted:         DENIED (FAIL-CLOSED)');
  });
});
