/**
 * Standard WolverineDB Error Codes (WDB1xx to WDB7xx)
 */
export enum WolverineErrorCode {
  // WDB1xx: Protocol / Binary / Serialization Errors
  INVALID_MAGIC_HEADER = 'WDB101',
  UNSORTED_FIELD_TAGS = 'WDB102',
  DUPLICATE_FIELD_TAG = 'WDB103',
  UNKNOWN_TYPE_TAG = 'WDB104',
  MALFORMED_FIELD_PAYLOAD = 'WDB105',
  INVALID_DECIMAL_FORMAT = 'WDB106',
  INVALID_JSON_C14N = 'WDB107',
  INVALID_PRIMARY_KEY_TUPLE = 'WDB108',
  UNKNOWN_RECORD_TYPE = 'WDB109',

  // WDB2xx: Database Adapter Errors
  DATABASE_CONNECTION_ERROR = 'WDB201',
  QUERY_EXECUTION_ERROR = 'WDB202',
  SCHEMA_MIGRATION_ERROR = 'WDB203',
  MISSING_PRIMARY_KEY = 'WDB204',
  TRIGGER_INSTALLATION_ERROR = 'WDB205',

  // WDB3xx: Integrity / Hash / Merkle Errors
  CHANGE_HASH_MISMATCH = 'WDB301',
  VERSION_HASH_MISMATCH = 'WDB302',
  MERKLE_ROOT_MISMATCH = 'WDB303',
  INVALID_INCLUSION_PROOF = 'WDB304',
  HISTORY_MUTATION_DETECTED = 'WDB305',
  MISSING_PREDECEASED_HASH = 'WDB306',

  // WDB4xx: Anchor Errors
  ANCHOR_UNAVAILABLE = 'WDB401',
  ANCHOR_VERIFICATION_FAILED = 'WDB402',

  // WDB5xx: Recovery Engine Errors
  RECOVERY_PROPOSAL_FAILED = 'WDB501',
  UNTRUSTED_RECOVERY_BASIS = 'WDB502',
  INDETERMINATE_RECOVERY_STATE = 'WDB503',
  CORRECTIVE_TRANSACTION_FAILED = 'WDB504',

  // WDB6xx: Authorization / Provenance Errors
  MISSING_PROVENANCE_ENVELOPE = 'WDB601',
  UNAUTHORIZED_MUTATION = 'WDB602',
  INVALID_APPROVAL_SIGNATURE = 'WDB603',
  UNTRUSTED_APPROVER_KEY = 'WDB604',
  REQUESTER_IS_APPROVER = 'WDB605',
  EXPIRED_APPROVAL_ENVELOPE = 'WDB606',
  REPLAYED_APPROVAL_NONCE = 'WDB607',

  // WDB7xx: Configuration Errors
  INVALID_CONFIGURATION = 'WDB701',
  MISSING_SECRET_KEY = 'WDB702',
}
